version: '2'
services:
  app:
    extends:
      file: services.yml
      service: app
    image: app:<%= @stand.short_reference %>
    volumes_from:
      - data
    depends_on:
      - data
    links:
      - mail

  data:
    extends:
      file: services.yml
      service: data

  mail:
    mem_limit: 16m
    image: mailhog/mailhog
